// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gossip.v1.proto

package gossip_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PullMembersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullMembersRequest) Reset()         { *m = PullMembersRequest{} }
func (m *PullMembersRequest) String() string { return proto.CompactTextString(m) }
func (*PullMembersRequest) ProtoMessage()    {}
func (*PullMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gossip_v1_4a10995857f8d665, []int{0}
}
func (m *PullMembersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullMembersRequest.Unmarshal(m, b)
}
func (m *PullMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullMembersRequest.Marshal(b, m, deterministic)
}
func (dst *PullMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullMembersRequest.Merge(dst, src)
}
func (m *PullMembersRequest) XXX_Size() int {
	return xxx_messageInfo_PullMembersRequest.Size(m)
}
func (m *PullMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullMembersRequest proto.InternalMessageInfo

type PullMembersResponse struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Members              []*Member `protobuf:"bytes,2,rep,name=members" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PullMembersResponse) Reset()         { *m = PullMembersResponse{} }
func (m *PullMembersResponse) String() string { return proto.CompactTextString(m) }
func (*PullMembersResponse) ProtoMessage()    {}
func (*PullMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gossip_v1_4a10995857f8d665, []int{1}
}
func (m *PullMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullMembersResponse.Unmarshal(m, b)
}
func (m *PullMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullMembersResponse.Marshal(b, m, deterministic)
}
func (dst *PullMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullMembersResponse.Merge(dst, src)
}
func (m *PullMembersResponse) XXX_Size() int {
	return xxx_messageInfo_PullMembersResponse.Size(m)
}
func (m *PullMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PullMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PullMembersResponse proto.InternalMessageInfo

func (m *PullMembersResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PullMembersResponse) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

type MembersUpdate struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Members              []*Member `protobuf:"bytes,3,rep,name=members" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MembersUpdate) Reset()         { *m = MembersUpdate{} }
func (m *MembersUpdate) String() string { return proto.CompactTextString(m) }
func (*MembersUpdate) ProtoMessage()    {}
func (*MembersUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_gossip_v1_4a10995857f8d665, []int{2}
}
func (m *MembersUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MembersUpdate.Unmarshal(m, b)
}
func (m *MembersUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MembersUpdate.Marshal(b, m, deterministic)
}
func (dst *MembersUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MembersUpdate.Merge(dst, src)
}
func (m *MembersUpdate) XXX_Size() int {
	return xxx_messageInfo_MembersUpdate.Size(m)
}
func (m *MembersUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_MembersUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_MembersUpdate proto.InternalMessageInfo

func (m *MembersUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MembersUpdate) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

type Member struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	Index                uint64   `protobuf:"varint,4,opt,name=index" json:"index,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	StartTime            int64    `protobuf:"varint,6,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_gossip_v1_4a10995857f8d665, []int{3}
}
func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (dst *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(dst, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Member) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Member) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Member) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Member) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Member) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

type Heartbeat struct {
	Originator           *Member  `protobuf:"bytes,1,opt,name=originator" json:"originator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_gossip_v1_4a10995857f8d665, []int{4}
}
func (m *Heartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heartbeat.Unmarshal(m, b)
}
func (m *Heartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heartbeat.Marshal(b, m, deterministic)
}
func (dst *Heartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heartbeat.Merge(dst, src)
}
func (m *Heartbeat) XXX_Size() int {
	return xxx_messageInfo_Heartbeat.Size(m)
}
func (m *Heartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Heartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Heartbeat proto.InternalMessageInfo

func (m *Heartbeat) GetOriginator() *Member {
	if m != nil {
		return m.Originator
	}
	return nil
}

type JoinRequest struct {
	Origiator            *Member  `protobuf:"bytes,1,opt,name=origiator" json:"origiator,omitempty"`
	DestinationHost      string   `protobuf:"bytes,2,opt,name=destination_host,json=destinationHost" json:"destination_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gossip_v1_4a10995857f8d665, []int{5}
}
func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (dst *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(dst, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetOrigiator() *Member {
	if m != nil {
		return m.Origiator
	}
	return nil
}

func (m *JoinRequest) GetDestinationHost() string {
	if m != nil {
		return m.DestinationHost
	}
	return ""
}

type JoinResponse struct {
	OriginatorHost       string    `protobuf:"bytes,1,opt,name=originator_host,json=originatorHost" json:"originator_host,omitempty"`
	Members              []*Member `protobuf:"bytes,3,rep,name=members" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *JoinResponse) Reset()         { *m = JoinResponse{} }
func (m *JoinResponse) String() string { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()    {}
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gossip_v1_4a10995857f8d665, []int{6}
}
func (m *JoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResponse.Unmarshal(m, b)
}
func (m *JoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResponse.Marshal(b, m, deterministic)
}
func (dst *JoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResponse.Merge(dst, src)
}
func (m *JoinResponse) XXX_Size() int {
	return xxx_messageInfo_JoinResponse.Size(m)
}
func (m *JoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResponse proto.InternalMessageInfo

func (m *JoinResponse) GetOriginatorHost() string {
	if m != nil {
		return m.OriginatorHost
	}
	return ""
}

func (m *JoinResponse) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func init() {
	proto.RegisterType((*PullMembersRequest)(nil), "gossip.v1.PullMembersRequest")
	proto.RegisterType((*PullMembersResponse)(nil), "gossip.v1.PullMembersResponse")
	proto.RegisterType((*MembersUpdate)(nil), "gossip.v1.MembersUpdate")
	proto.RegisterType((*Member)(nil), "gossip.v1.Member")
	proto.RegisterType((*Heartbeat)(nil), "gossip.v1.Heartbeat")
	proto.RegisterType((*JoinRequest)(nil), "gossip.v1.JoinRequest")
	proto.RegisterType((*JoinResponse)(nil), "gossip.v1.JoinResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GossipClient is the client API for Gossip service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GossipClient interface {
	PullMembers(ctx context.Context, in *PullMembersRequest, opts ...grpc.CallOption) (*PullMembersResponse, error)
	PushHeartbeat(ctx context.Context, in *Heartbeat, opts ...grpc.CallOption) (*empty.Empty, error)
	PushMembersUpdate(ctx context.Context, in *MembersUpdate, opts ...grpc.CallOption) (*empty.Empty, error)
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
}

type gossipClient struct {
	cc *grpc.ClientConn
}

func NewGossipClient(cc *grpc.ClientConn) GossipClient {
	return &gossipClient{cc}
}

func (c *gossipClient) PullMembers(ctx context.Context, in *PullMembersRequest, opts ...grpc.CallOption) (*PullMembersResponse, error) {
	out := new(PullMembersResponse)
	err := c.cc.Invoke(ctx, "/gossip.v1.Gossip/PullMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gossipClient) PushHeartbeat(ctx context.Context, in *Heartbeat, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/gossip.v1.Gossip/PushHeartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gossipClient) PushMembersUpdate(ctx context.Context, in *MembersUpdate, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/gossip.v1.Gossip/PushMembersUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gossipClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, "/gossip.v1.Gossip/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Gossip service

type GossipServer interface {
	PullMembers(context.Context, *PullMembersRequest) (*PullMembersResponse, error)
	PushHeartbeat(context.Context, *Heartbeat) (*empty.Empty, error)
	PushMembersUpdate(context.Context, *MembersUpdate) (*empty.Empty, error)
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
}

func RegisterGossipServer(s *grpc.Server, srv GossipServer) {
	s.RegisterService(&_Gossip_serviceDesc, srv)
}

func _Gossip_PullMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServer).PullMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gossip.v1.Gossip/PullMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServer).PullMembers(ctx, req.(*PullMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gossip_PushHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Heartbeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServer).PushHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gossip.v1.Gossip/PushHeartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServer).PushHeartbeat(ctx, req.(*Heartbeat))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gossip_PushMembersUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MembersUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServer).PushMembersUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gossip.v1.Gossip/PushMembersUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServer).PushMembersUpdate(ctx, req.(*MembersUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gossip_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gossip.v1.Gossip/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gossip_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gossip.v1.Gossip",
	HandlerType: (*GossipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PullMembers",
			Handler:    _Gossip_PullMembers_Handler,
		},
		{
			MethodName: "PushHeartbeat",
			Handler:    _Gossip_PushHeartbeat_Handler,
		},
		{
			MethodName: "PushMembersUpdate",
			Handler:    _Gossip_PushMembersUpdate_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _Gossip_Join_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gossip.v1.proto",
}

func init() { proto.RegisterFile("gossip.v1.proto", fileDescriptor_gossip_v1_4a10995857f8d665) }

var fileDescriptor_gossip_v1_4a10995857f8d665 = []byte{
	// 430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0x97, 0x36, 0x0d, 0xca, 0x95, 0x51, 0x76, 0x54, 0xc3, 0x0a, 0x0c, 0x45, 0x7e, 0x21,
	0x08, 0x29, 0xd5, 0xc6, 0x13, 0x2f, 0xf0, 0x84, 0x36, 0x21, 0x81, 0xaa, 0x08, 0x78, 0x9d, 0x12,
	0xc5, 0x64, 0x96, 0x9a, 0x38, 0xc4, 0x0e, 0x82, 0x4f, 0xc2, 0x13, 0xdf, 0x15, 0xd9, 0x4e, 0x17,
	0x4f, 0x1d, 0xab, 0xf6, 0xe6, 0xfc, 0xfe, 0x77, 0xff, 0x9c, 0xef, 0x7c, 0xb0, 0xa8, 0x84, 0x94,
	0xbc, 0x4d, 0x7f, 0x9e, 0xa6, 0x6d, 0x27, 0x94, 0xc0, 0xf0, 0x1a, 0x44, 0xcf, 0x2a, 0x21, 0xaa,
	0x0d, 0x5b, 0x19, 0xa1, 0xe8, 0xbf, 0xaf, 0x58, 0xdd, 0xaa, 0xdf, 0x36, 0x8e, 0x2e, 0x01, 0xd7,
	0xfd, 0x66, 0xf3, 0x89, 0xd5, 0x05, 0xeb, 0x64, 0xc6, 0x7e, 0xf4, 0x4c, 0x2a, 0xfa, 0x0d, 0x9e,
	0xdc, 0xa0, 0xb2, 0x15, 0x8d, 0x64, 0x88, 0xe0, 0x37, 0x79, 0xcd, 0x88, 0x17, 0x7b, 0x49, 0x98,
	0x99, 0x33, 0xbe, 0x86, 0x07, 0xb5, 0x0d, 0x23, 0x93, 0x78, 0x9a, 0xcc, 0xcf, 0x8e, 0xd2, 0xb1,
	0x16, 0x6b, 0x90, 0x6d, 0x23, 0xe8, 0x1a, 0x0e, 0x07, 0xcf, 0xaf, 0x6d, 0x99, 0xab, 0xbd, 0x8e,
	0xd3, 0xbd, 0x8e, 0x7f, 0x3c, 0x08, 0x2c, 0xbb, 0xd5, 0x0b, 0xc1, 0xbf, 0x12, 0x52, 0x91, 0x89,
	0x65, 0xfa, 0xac, 0x59, 0x2b, 0x3a, 0x45, 0xa6, 0xb1, 0x97, 0xcc, 0x32, 0x73, 0xc6, 0x25, 0xcc,
	0x78, 0x53, 0xb2, 0x5f, 0xc4, 0x8f, 0xbd, 0xc4, 0xcf, 0xec, 0x07, 0x3e, 0x87, 0x50, 0xf1, 0x9a,
	0x49, 0x95, 0xd7, 0x2d, 0x99, 0xc5, 0x5e, 0x32, 0xcd, 0x46, 0x80, 0x27, 0x00, 0x52, 0xe5, 0x9d,
	0xba, 0xd4, 0x88, 0x04, 0x56, 0x36, 0xe4, 0x0b, 0xaf, 0x19, 0x7d, 0x07, 0xe1, 0x05, 0xcb, 0x3b,
	0x55, 0xb0, 0x5c, 0xe1, 0x29, 0x80, 0xe8, 0x78, 0xc5, 0x9b, 0x5c, 0x89, 0xce, 0x54, 0x78, 0xeb,
	0xb5, 0x9c, 0x20, 0xca, 0x61, 0xfe, 0x51, 0xf0, 0x66, 0x18, 0x09, 0xae, 0x20, 0x34, 0xe2, 0xdd,
	0x06, 0x63, 0x0c, 0xbe, 0x82, 0xc7, 0x25, 0x93, 0x4a, 0xbb, 0x71, 0xd1, 0x5c, 0x3a, 0x6d, 0x58,
	0x38, 0xfc, 0x42, 0x48, 0x45, 0x4b, 0x78, 0x68, 0x7f, 0x35, 0xcc, 0xf9, 0x25, 0x2c, 0xc6, 0x42,
	0x6c, 0xa6, 0x6d, 0xea, 0xa3, 0x11, 0xeb, 0xc4, 0x7b, 0x8d, 0xea, 0xec, 0xef, 0x04, 0x82, 0x73,
	0xa3, 0xe2, 0x67, 0x98, 0x3b, 0xef, 0x0b, 0x4f, 0x9c, 0xac, 0xdd, 0xd7, 0x18, 0xbd, 0xf8, 0x9f,
	0x6c, 0xcb, 0xa5, 0x07, 0xf8, 0x1e, 0x0e, 0xd7, 0xbd, 0xbc, 0x1a, 0xfb, 0xbd, 0x74, 0x52, 0xae,
	0x69, 0x74, 0x9c, 0xda, 0x55, 0x48, 0xb7, 0xab, 0x90, 0x7e, 0xd0, 0xab, 0x40, 0x0f, 0xf0, 0x1c,
	0x8e, 0xb4, 0xc1, 0xcd, 0xc7, 0x49, 0x76, 0x2e, 0x33, 0x28, 0x77, 0x18, 0xbd, 0x05, 0x5f, 0xb7,
	0x12, 0x8f, 0x9d, 0x5c, 0x67, 0x8c, 0xd1, 0xd3, 0x1d, 0xbe, 0xbd, 0x44, 0x11, 0x18, 0xb3, 0x37,
	0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x79, 0x85, 0x86, 0xe3, 0xcc, 0x03, 0x00, 0x00,
}
